name: Build and deploy site

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Commit built files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist .nojekyll
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update site [skip ci]"
            git push origin HEAD:gh-pages
          fi

